import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  topHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
    height: 50,
    backgroundColor: '#000000',
  },
  topHeaderItems: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 60,
  },
  botHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    height: 20,
    backgroundColor: '#000000',
  },
  botHeaderItems: {
    color: '#ffffff',
    marginHorizontal: 25,
    fontSize: 16,
  },

  mainContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    margin: 20,
    width: '100%',
    marginHorizontal: 'auto',
  },

  mainCategory: {
    width: '100%',
    maxWidth: 800,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    fontSize: 12,
    paddingVertical: 20,
    paddingHorizontal: 40,
  },
  mainText: {
    color: '#999999',
  },
  dot: {
    height: 3,
    width: 3,
    backgroundColor: 'green',
    borderRadius: 1.5,
  },

  mainButtonsContainer: {
    width: '100%',
    maxWidth: 800,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  iconsButton: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#777777',
    fontSize: 12,
  },
  playButton: {
    width: 125,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    color: '#000000',
    paddingVertical: 6,
    paddingHorizontal: 12,
    fontSize: 16,
    fontWeight: '500',
    borderRadius: 3,
  },
});
